---

- hosts: all
  remote_user: root
  become: true
  vars_files:
    - vars/main.yml

  tasks:
    - block:
      - include: tasks/register_release_variables.yml
      - include: tasks/create_new_release_dir.yml
      - include: tasks/clone_repo.yml
      - include: tasks/mark_release.yml
      - include: tasks/install_composer_deps.yml
      - include: tasks/set_owner_and_group.yml dir_to_chown="{{ new_release_dir }}"
      - include: tasks/set_correct_permissions.yml dir="{{ new_release_dir }}"
      - include: tasks/check_that_folder_is_writable.yml dir_to_check="{{ new_release_dir }}/bootstrap/cache"
      - include: tasks/link_storage.yml
      - include: tasks/link_env.yml
      # - include: tasks/migrate_db.yml
      - include: tasks/bless_new_release.yml
      - include: tasks/leave_most_10_recent_releases.yml
      # - include: tasks/inform_newrelic.yml
      rescue:
        - include: tasks/rollback.yml
{"downloadUrl":"https://d3v5qmgpw891au.cloudfront.net/profile/1CDfyqYQfPRs2m1a1VSMaD89GZ63Mwu78N/7a6998d3f4ab421e9619627b33f1ce6b","fields":[{"key":"key","value":"profile/1CDfyqYQfPRs2m1a1VSMaD89GZ63Mwu78N/7a6998d3f4ab421e9619627b33f1ce6b"},{"key":"X-Amz-Credential","value":"AKIA3NG2JXZC3SY2WNXE/20191225/ap-east-1/s3/aws4_request"},{"key":"X-Amz-Date","value":"20191225T002608Z"},{"key":"X-Amz-Algorithm","value":"AWS4-HMAC-SHA256"},{"key":"Policy","value":"eyAiZXhwaXJhdGlvbiI6ICIyMDE5LTEyLTI1VDAwOjU2OjA4LjAwMFoiLAogICJjb25kaXRpb25zIjogWwogICAgeyJidWNrZXQiOiAiYmNtLWhrIn0sCiAgICBbImVxIiwgIiRrZXkiLCAicHJvZmlsZS8xQ0RmeXFZUWZQUnMybTFhMVZTTWFEODlHWjYzTXd1NzhOLzdhNjk5OGQzZjRhYjQyMWU5NjE5NjI3YjMzZjFjZTZiIl0sCiAgICBbImNvbnRlbnQtbGVuZ3RoLXJhbmdlIiwgMSwgNjcxMDg4NjRdLAogICAgeyJ4LWFtei1jcmVkZW50aWFsIjogIkFLSUEzTkcySlhaQzNTWTJXTlhFLzIwMTkxMjI1L2FwLWVhc3QtMS9zMy9hd3M0X3JlcXVlc3QifSwKICAgIHsieC1hbXotYWxnb3JpdGhtIjogIkFXUzQtSE1BQy1TSEEyNTYifSwKICAgIHsieC1hbXotZGF0ZSI6ICIyMDE5MTIyNVQwMDI2MDhaIiB9CiAgXQp9"},{"key":"X-Amz-Signature","value":"dc4f9003a5613f72ee7b13154deaa503dcc23eb233d6fb651e12b907926f86ce"}],"postUrl":"https://bcm-hk.s3.ap-east-1.amazonaws.com/"}
